name: detecting-biased-language
jobs:
    Detect-Biased-language:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - env:
              # HANNIBAL_TOKEN: ${{secrets.PINK_PANTHER_HANNIBAL_TOKEN_D04092021}}
            - run: pwd
            - run: echo "SECRET"
            # - run: echo ${{env.HANNIBAL_TOKEN}}
