name: detecting-biased-language
description: 'lint for biased lang'
inputs:
    token:
        description: 'Github Token'
    path:
        description: 'Project Path'
    url:
        description: 'Project URL'
    repo:
        description: 'Project Repo'
# runs:
#     using: 'docker'
#     image: 'Dockerfile'
# runs:
#     using: 'docker'
#     image: 'docker://ghcr.io/lng-org/biased_lang:v1.test'
runs:
    using: 'composite'
    steps:
        - run: echo "${{inputs.token}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
          shell: bash
        - run: docker pull ghcr.io/lng-org/biased_lang:v2.test
          shell: bash
        - run: echo ${{inputs.path}}
          shell: bash
        - run: docker run --name pinkpanther -e GITHUB_WORKSPACE=${{inputs.path}} -e GITHUB_URL=${{inputs.url}} -e GITHUB_REPO=${{inputs.repo}} ghcr.io/lng-org/biased_lang:v1.test
          shell: bash
        - run: docker logs -f pinkpanther
          shell: bash
