stages:
    - test
    - gitlab:publish:test
    - gitlab:test
    - gitlab:publish:production
    - github:publish:test
    - github:test
    - github:publish:production

variables:
    PRODUCTION_PATH: docker:v1/registry/prefix/eng-effectiveness
    PRODUCTION_URL: docker.repo.splunkdev.net/eng-effectiveness

.docker_prod_build_rules:
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
              - run_json.py
              - constants.py
              - utils/
              - tools/
              - Dockerfile
              - .dockerignore
              - requirements.txt
              - word_list.csv

.docker_publish: &docker_publish
    retry: 2
    before_script:
        - creds-helper init
        - eval $(creds-helper docker --eval ${DOCKER_PATH})
    script:
        - docker build -t ${TAG} -f ${DOCKERFILE} .
        - docker push ${TAG}

pytest:
    stage: test
    script:
        - apt-get update -qy
        - apt-get install -y python3.7 python3-pip
        - apt-get install ripgrep
        - pip3 install -r requirements.txt
        - python3 run_json.py --path=./tests/mock_repo --mode=check --excluded_dirs_path=.test_excluded_dirs --excluded_files_path=.test_excluded_files --err_file=err_biased_lang.log
        - pytest

# Can only run production_build_push_test stage on protected branch (main)
# due to Docker registry policy
gitlab_publish_test:
    <<: *docker_publish
    stage: gitlab:publish:test
    variables:
        DOCKER_PATH: ${PRODUCTION_PATH}
        DOCKERFILE: Dockerfile
        TAG: '${PRODUCTION_URL}/ci-container-biased-lang-test:python-3.7-buster'
    extends: .docker_prod_build_rules

gitlab_test:
    stage: gitlab:test
    trigger:
        project: engprod/saucelabs-monitoring
        branch: liyangw/test-pinkpanther
        strategy: depend
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'

# Can only run production_build_push_release stage on protected branch (main)
# due to Docker registry policy
gitlab_publish_production:
    <<: *docker_publish
    stage: gitlab:publish:production
    variables:
        DOCKER_PATH: ${PRODUCTION_PATH}
        DOCKERFILE: Dockerfile
        TAG: '${PRODUCTION_URL}/ci-container-biased-lang:python-3.7-buster'
    extends: .docker_prod_build_rules

github_publish_test:
    stage: github:publish:test
    variables:
        DOCKERFILE: Dockerfile.gh
        TAG: ghcr.io/splunk/biased_lang:test
    script:
        - echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
        - docker build -t ${TAG} -f ${DOCKERFILE} .
        - docker push ${TAG}
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'

github_test:
    stage: github:test
    script:
        - apt-get update -qy
        - apt-get install -y python3.7 python3-pip
        - pip3 install requests
        - python3 check_github.py $GH_TOKEN
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'

github_publish_production:
    stage: github:publish:production
    variables:
        DOCKERFILE: Dockerfile.gh
        TAG: ghcr.io/splunk/biased_lang
    script:
        - echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
        - docker build -t ${TAG} -f ${DOCKERFILE} .
        - docker push ${TAG}
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
