stages:
  - test
  - gitlab:publish:test
  - gitlab:test
  - gitlab:publish:production
  - github:publish:test
  - github:test
  - github:publish:production

variables:
  PRODUCTION_PATH: docker:v1/registry/prefix/eng-effectiveness
  PRODUCTION_URL: docker.repo.splunkdev.net/eng-effectiveness

.docker_prod_build_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - run_json.py
        - constants.py
        - utils/*
        - tools/*
        - Dockerfile
        - .dockerignore
        - .gitlab-ci.yml
        - requirements.txt
        - word_list.csv

.docker_build_push: &docker_build_push
  script:
    - docker build -t ${TAG} -f ${DOCKERFILE} .
    - docker build -t ${SHA_TAG} -f ${DOCKERFILE} .
    - docker push ${TAG}
    - docker push ${SHA_TAG}

.gitlab_docker_publish: &gitlab_docker_publish
  <<: *docker_build_push
  retry: 2
  before_script:
    - creds-helper init
    - eval $(creds-helper docker --eval ${DOCKER_PATH})

.github_docker_publish: &github_docker_publish
  <<: *docker_build_push
  retry: 2
  before_script:
    - echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin

pytest:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3.7 python3-pip
    - apt-get install ripgrep
    - pip3 install -r requirements.txt
    - python3 run_json.py --path=./tests/mock_repo --mode=check --err_file=err_biased_lang.log
    - coverage run --omit '/usr/*' -m pytest && coverage report -m

# Can only run production_build_push_test stage on protected branch (main)
# due to Docker registry policy
gitlab_publish_test:
  <<: *gitlab_docker_publish
  stage: gitlab:publish:test
  variables:
    DOCKER_PATH: ${PRODUCTION_PATH}
    DOCKERFILE: Dockerfile
    TAG: '${PRODUCTION_URL}/ci-container-biased-lang-test:python-3.7-buster'
    SHA_TAG: '${PRODUCTION_URL}/ci-container-biased-lang-test:python-3.7-buster-$CI_COMMIT_SHA'
  extends: .docker_prod_build_rules

gitlab_test:
  stage: gitlab:test
  trigger:
    project: engprod/saucelabs-monitoring
    branch: liyangw/test-biasedlang
    strategy: depend
  extends: .docker_prod_build_rules

# Can only run production_build_push_release stage on protected branch (main)
# due to Docker registry policy
gitlab_publish_production:
  <<: *gitlab_docker_publish
  stage: gitlab:publish:production
  variables:
    DOCKER_PATH: ${PRODUCTION_PATH}
    DOCKERFILE: Dockerfile
    TAG: '${PRODUCTION_URL}/ci-container-biased-lang:python-3.7-buster'
    SHA_TAG: '${PRODUCTION_URL}/ci-container-biased-lang:python-3.7-buster-$CI_COMMIT_SHA'
  extends: .docker_prod_build_rules

github_publish_test:
  <<: *github_docker_publish
  stage: github:publish:test
  variables:
    DOCKERFILE: Dockerfile.gh
    TAG: ghcr.io/splunk/biased_lang:test
    SHA_TAG: ghcr.io/splunk/biased_lang:test-$CI_COMMIT_SHA
  extends: .docker_prod_build_rules

github_test:
  stage: github:test
  script:
    - apt-get update -qy
    - apt-get install -y python3.7 python3-pip
    - pip3 install requests
    - python3 check_github.py $GH_TOKEN
  extends: .docker_prod_build_rules

github_publish_production:
  <<: *github_docker_publish
  stage: github:publish:production
  variables:
    DOCKERFILE: Dockerfile.gh
    TAG: ghcr.io/splunk/biased_lang
    SHA_TAG: ghcr.io/splunk/biased_lang:$CI_COMMIT_SHA
  extends: .docker_prod_build_rules
